Repository hybridauth/hybridauth, pull requests merged in 2018-04, with the labels that each got.

#941 #771: Updated Vkontakte provider.
  src/Provider/Vkontakte.php
Labels: Provider

#944 Make possible OpenID auth via POST
  src/Adapter/OpenID.php
Labels: Improvement

#947 Improve initialize of OAuth1 provider
  src/Adapter/OAuth1.php
Labels: Improvement

#953 [Discord] Makes display name more unique.
  src/Provider/Discord.php
Labels: Provider

#946 Added EXAMPLE_07, opening provider logins in a popup
  .gitignore
  examples/README.md
  examples/example_07/callback.php
  examples/example_07/config.php
  examples/example_07/index.php
Labels: Documentation, Improvement
