Repository hybridauth/hybridauth, pull requests merged in 2019-09, with the labels that each got.

#1066 Allow POST method in OAuth2 authentification
  src/Adapter/OAuth2.php
Labels: tag: new feature :rocket:

#1112 added Telegram.
  src/Provider/Telegram.php
Labels: tag: provider :house:

#1106 Update OAuth2.php
  src/Adapter/OAuth2.php
Labels: tag: documentation :memo:, tag: enhancement :100:

#1070 Add support for multipart requests for video upload support
  src/Adapter/AbstractAdapter.php
  src/Adapter/AdapterInterface.php
  src/Adapter/OAuth1.php
  src/Adapter/OAuth2.php
  src/HttpClient/Curl.php
  src/HttpClient/Guzzle.php
  src/HttpClient/HttpClientInterface.php
Labels: tag: new feature :rocket:

#1113 [OAuth2] Re-login when access token is expired without refresh token
  hybridauth/Hybrid/Provider_Adapter.php
  hybridauth/Hybrid/Provider_Model.php
  hybridauth/Hybrid/Provider_Model_OAuth2.php
Labels: tag: bug fix :sunglasses:, tag: enhancement :100:
