Repository hybridauth/hybridauth, pull requests merged in 2020-11, with the labels that each got.

#1254 Fix (only) error coming up in PHP8 linting, with 3rd party OpenID lib
  src/Thirdparty/OpenID/LightOpenID.php
Labels: tag: bug fix :sunglasses:

#1257 Various fixes from PHPStorm scan
  src/Adapter/OpenID.php
  src/Data/Parser.php
  src/HttpClient/Curl.php
  src/HttpClient/Guzzle.php
  src/Provider/Apple.php
  src/Provider/Authentiq.php
  src/Provider/Facebook.php
  src/Provider/MicrosoftGraph.php
  src/Provider/Telegram.php
  src/Provider/WeChat.php
Labels: tag: enhancement :100:

#1255 Implemented Token Exchange for Instagram
  src/Adapter/AbstractAdapter.php
  src/Adapter/AdapterInterface.php
  src/Adapter/OAuth1.php
  src/Adapter/OAuth2.php
  src/Provider/Facebook.php
  src/Provider/Instagram.php
Labels: tag: new feature :rocket:, tag: provider :house:

#1263 Upgrade Travis configuration
  .travis.yml
  composer.json
Labels: tag: enhancement :100:
