Repository hybridauth/hybridauth, pull requests merged in 2021-01, with the labels that each got.

#1282 Fix to Instagram Token exchange
  src/Provider/Instagram.php
Labels: tag: bug fix :sunglasses:, tag: provider :house:

#1283 Move apple related deps to suggest section
  composer.json
Labels: tag: enhancement :100:

#1275 Direct Message to Twitter
  src/Thirdparty/OAuth/OAuthRequest.php
Labels: tag: bug fix :sunglasses:
